### PR TITLE
Update Package Cache

### PR DESCRIPTION
**Pull request by zkamvar**
@sarahkaspar this updates the package cache to avoid the error that was seen in https://github.com/carpentries/workbench/issues/40

I have also removed the `renv/` folder inside of the `episodes/` folder. This was caused by a bug in sandpaper that I will fix in the next version: https://github.com/carpentries/sandpaper/issues/391

One other issue that I am seeing is that you have two setup documents in the learner folder:

https://github.com/sarahkaspar/biostatistics-course/blob/edadde9faeb94c9ab2cb490477656240e32be54d/learners/setup.Rmd and https://github.com/sarahkaspar/biostatistics-course/blob/edadde9faeb94c9ab2cb490477656240e32be54d/learners/setup.md

The Workbench considers the name of these files identical (because it treats markdown and Rmarkdown the same). Is there a reason for having two? I noticed that you are using the markdown version in the config, I am removing the R Markdown version.

### CODE REVIEW

**Comment by zkamvar** [comment]
Additionally, if you want to be able to update the package cache without cloning locally, you can add a `SANDPAPER_WORKFLOW` token to your repository secrets, as laid out in this comment here: https://github.com/sarahkaspar/biostatistics-course/actions/runs/4109320026/attempts/1#summary-11152963877

**Comment by sarahkaspar** [comment]
Hi Zhian, 
Thank you so much for taking the time and fixing these things!  
It worked and the site is now up: https://sarahkaspar.github.io/biostatistics-course/
I'm really happy that the workbench is coming - I have been looking for an environment like this for quite some time.

Can I bother you with one more issue? Now that the website is up, the png-images that I store in the episodes/fig folder are only shown in the instructor view. Locally (on my computer in the RStudio viewer) all looks fine, in both learner and instructor view. I'd be very grateful for your feedback.

**Comment by tobyhodges** [comment]
> Now that the website is up, the png-images that I store in the episodes/fig folder are only shown in the instructor view. Locally (on my computer in the RStudio viewer) all looks fine, in both learner and instructor view. I'd be very grateful for your feedback.

Hi @sarahkaspar you could try removing the `/` at the start of the file paths you are using for images in your episodes. Paths beginning `fig/` should work better, I think?

**Comment by sarahkaspar** [comment]
Yes, they do :) The lesson looks good now. Thank you for coming back to this Toby!

**Pull request merged**
